services:
  nginx:
    ports:
      - "8090:80"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    user: "${UID}:${GID}"

  phpmyadmin:
    ports:
      - 8091:80
